baseurl = "https://angry-williams-842034.netlify.app/"
author = "Helmholtz HZI"
copyright = "Copyright (c) 2020 Helmholtz HZI"
canonifyurls = true
paginate = 3
theme="hugo-finite"

# multilingual
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Influenza Survey"
    weight = 1
    sponsor_url = "https://www.helmholtz.de/en"
    bio_full = ""
    blogName = "[Blog Name] blog"
    blogDescription = "The blog description goes here"
    studiesName = "[Studies Name] Studies"
    studiesDescription = "Studies description goes here"
    publicationName = "Publications"
    publicationDescription = "Publications description goes here"
  [languages.de]
    languageName = "Deutsch"
    title = "LEOSS.sero-survey"
    weight = 2
    sponsor_url = "https://www.helmholtz.de"
    bio_full = ""
    blogName = ""
    blogDescription = ""
    studiesName = ""
    studiesDescription = ""
    publicationName = ""
    publicationDescription = ""


[params]
logo = "img/hzi_logo_white.png"
sponsor = "Helmholtz HZI"
# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
#date_format = "2 January 2006"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

twitter_feed = "serohub"

# Number of posts to show on main page.
default_count = 2

sharing = true
leaflet_enable = true
mapbox_token = "pk.eyJ1Ijoic3RlcGhsb2NrZSIsImEiOiJjazlzOWg4Nm4wMnloM2Ztb3ZqcDl1bnZiIn0.TbIjIGJN69vEyaINwJTclA"
leaflet_central_lat = 52.5200
leaflet_central_long = 13.4050

[params.dashboard]
url = "../sample.html"
button = "Sample dashboard"

[markup]
  [markup.highlight]
    style = "manni"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# [[params.education]]
#   course = "Bachelor in Civil Law"
#   institution = "University of Orléans"
#   year = 1626

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:email@helmholtz-hzi.de"
  text = "email@helmholtz-hzi.de"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/"
  text = "@twitter"
  site = "Twitter"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/"
  text = "hzi-braunschweig/github"
  site = "GitHub"

# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[languages.en.menu.main]]
  name = "Publications"
  url = "/en/publication/"
  weight = 4
[[languages.de.menu.main]]
  name = "Veröffentlichungen"
  url = "/de/publication/"
  weight = 4

[[languages.en.menu.main]]
  name = "Studies"
  url = "/en/studies/"
  weight = 1
[[languages.de.menu.main]]
  name = "Studien"
  url = "/de/studies/"
  weight = 1


[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
mediaType = "application/json"
baseName = "studies"
isPlainText =  true
